"""Reason in stats

Revision ID: 609484fbe89c
Revises: d41f769fbebf
Create Date: 2025-08-13 14:58:32.140351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609484fbe89c'
down_revision: Union[str, Sequence[str], None] = 'd41f769fbebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('reason', sa.Enum('PICK', 'FILL_CUP', name='statreason'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'reason')
    # ### end Alembic commands ###
