"""initial

Revision ID: d41f769fbebf
Revises: 
Create Date: 2025-08-11 23:16:18.930561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41f769fbebf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tea',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('bags', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Enum('STAR_1', 'STAR_2', 'STAR_3', 'STAR_4', 'STAR_5', name='rating'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('use_sugar', sa.Boolean(), nullable=True),
    sa.Column('picked', sa.Integer(), nullable=True),
    sa.Column('tea_type', sa.Enum('GREEN', 'BLACK', 'WHITE', 'RED', 'HERBAL', 'OTHER', name='teatype'), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tea_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tea_id'], ['tea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    op.drop_table('tea')
    # ### end Alembic commands ###
